### ISSUE TITLE
Sync with Kodekit Platform

### ISSUE THREAD

**Issue by rmdstudio** [joomlatools/joomlatools-framework-tags#3]
Catch-all ticket to sync code with Kodekit Platform. Ticket will not include further feature development.

**Comment by johanjanssens** [comment]
@rmdstudio At present the code is expecting to be able to pass a 'model' identifier or model object to the listbox helper, see [code](https://github.com/joomlatools/joomlatools-framework-tags/blob/master/template/helper/listbox.php#L35). Joomlatools Framework cannot do this, changes have been made in Kodekit to allow for this. You will need to backport these changes.

Best approach is to create a specialise listbox helper for com:tags and implement the changes there. For the changes see following commit: https://github.com/timble/kodekit/commit/17dc27ed21c938e5206b39e12ecf133c18493036

**Comment by johanjanssens** [comment]
@rmdstudio Another change I made to tags. See: https://github.com/timble/kodekit-platform/commit/570f58afda6e467a49e2a80686fdcbbc1b029bb1 I'm no longer aliasing the layouts. This is not needed if you put the specific tag templates in the component that is integrating them. 

Please sync this change.

**Comment by rmdstudio** [comment]
@johanjanssens I am getting this error:

`Argument 1 passed to KDatabaseRowsetAbstract::insert() must implement interface KObjectHandlable, array given, called in /home/vagrant/Projects/joomlatools-framework-tags/controller/behavior/taggable.php on line 70 and defined`

this is what's causing it: 

```
$properties = array(
    'title' => $tag,
    'row'   => $entity->uuid,
);

$tags->insert($properties, $status);
```

What type of object do I need to use in this case? Apparently a simple array doesn't cut it.

**Comment by johanjanssens** [comment]
You need to create the row object based on the array and insert that. See: https://github.com/timble/kodekit/blob/master/code/database/rowset/abstract.php#L144

**Comment by rmdstudio** [comment]
@johanjanssens I think the following line is trying to obtain tags on an entity that is already deleted. Also it doesn't need to delete the tags. We just want to delete the relations. What is the proper way to do that. Could you point me to an example please? https://github.com/joomlatools/joomlatools-framework-tags/blob/master/controller/behavior/taggable.php#L94

**Comment by johanjanssens** [comment]
@rmdstudio 
1. Deleting relationships

An tag entity is build to handle deleting of it's own relations. The entity will also delete itself, it there are no additional relationships. See: https://github.com/joomlatools/joomlatools-framework-tags/blob/master/model/entity/tag.php#L69
1. Getting tags after entity is deleted

This is likely a difference between 3.x and 2.x version of framework. In 3.x entity data is not reset after the entity is deleted or modified. In 2.x is it is. If you change https://github.com/joomlatools/joomlatools-framework-tags/blob/master/controller/behavior/taggable.php#L29 to before.delete it should work ?

**Comment by rmdstudio** [comment]
I think the issue is that $entity->getTags() doesn't returns null on that entity even though it has tags associated with it. When I do a var_dump($entity) it shows a KModelEntityRowset entity set rather than a document entity set. That entity doesn't have the taggable behaviour. Any thoughts?

**Comment by rmdstudio** [comment]
oh never mind is is 

```
object(KModelEntityRowset)[1220]
  protected '_identity_column' => string 'id' (length=2)
  protected '_prototypable' => boolean true
  protected '_prototype' => 
    object(ComDocmanModelEntityDocument)[1225]
```

the entity is a document

**Comment by johanjanssens** [comment]
Can you try my suggestion above ?

**Comment by rmdstudio** [comment]
I tried using before.delete and I get `Call to a member function getStatus() on a non-object` at `$status = $entity->getStatus();`

**Comment by johanjanssens** [comment]
$context->result does not exist yet in this case, you need to do $entity = $this->getModel()->fetch(); to get it first.

**Comment by johanjanssens** [comment]
@rmdstudio i have synced the final changes to tags. Everything should now be working, the following PR is required in the framework. https://github.com/joomlatools/joomlatools-framework/pull/7 when testing make sure to switch your fw repo until this PR is merged.

**Comment by johanjanssens** [comment]
@rmdstudio  I think we can close this one no?

**Comment by rmdstudio** [comment]
I believe we can. I remember ercan reverted the code after discussion with you and it is working now.
